name: Test Multiline String

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (semver)'
        required: true
      chartVersion:
        description: 'Chart Version (semver)'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Env Variable
        run: |
          GITHUB_HEADER="Accept: application/vnd.github.v3+json"
          MILESTONE_BASE_URL=https://api.github.com/repos/xin-hedera/hedera-mirror-node/milestones
          
          description=$(curl -s -H "$GITHUB_HEADER" $MILESTONE_BASE_URL/2 | jq -r '.description' | sed 's/\r$//')
          echo DESCRIPTION1=\"$description\" > $GITHUB_ENV
          #echo "DESCRIPTION2=\"$description\"" > $GITHUB_ENV
      
      - name: Show Env Variable
        run: |
          echo "$DESCRIPTION1"
          echo "$DESCRIPTION2"
